name: CD

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  package-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Package source
        run: |
          zip -r snake-python.zip src requirements.txt README.md

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-python-release
          path: snake-python.zip

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: snake-python.zip
