name: Fluxo CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          source .venv/bin/activate
          flake8 **.py --max-line-length=250

      - name: Archive code
        uses: actions/upload-artifact@v4
        with:
          name: snake-src
          path: src/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Package source
        run: |
          zip -r snake-python.zip src requirements.txt README.md

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-python-release
          path: snake-python.zip